name: CI

on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: air-drop-functions-test-linux
  AZURE_FUNCTIONAPP_NAME_MAIN: air-drop-functions-linux
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '12.x'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install deps
        run: yarn

      - name: lint
        run: yarn lint

      - name: create db
        run: |
          cd docker
          docker-compose up -d
          cd ..

      - name: test
        run: yarn test

  deploy:
    needs: build
    if: ${{ github.event_name != 'pull_request' && contains(github.ref, 'test') }}

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install deps
        run: yarn

      - name: build
        run: yarn build

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy-main:
    needs: build
    if: ${{ github.event_name != 'pull_request' && contains(github.ref, 'main') }}

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install deps
        run: yarn

      - name: build
        run: yarn build

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_MAIN }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_MAIN }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
